spring:
  application:
    name: gateway-service
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: ${service.gateway.routes.user-service.uri}
              predicates:
                - Path=/user/**
            - id: product-service
              uri: ${service.gateway.routes.product-service.uri}
              predicates:
                - Path=/product/**
      default-filters:
        - AddResponseHeader=X-Gateway, Gateway-Service
server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
    com.microservices.reference.gateway_service: DEBUG

info:
  app:
    version: '0.0.1-SNAPSHOT'
  gradle:
    version: '8.14.3'

management:
  endpoints:
    web:
      exposure:
        include: "*"
service:
  gateway:
    routes:
      user-service:
        uri: http://localhost:8081
      product-service:
        uri: http://localhost:8082