spring:
  application:
    name: "common"

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    com.microservices.reference: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
