name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon --stacktrace

      - name: Run tests
        run: ./gradlew test --no-daemon --stacktrace

      # Opcional: publicar artefato build (jar)
      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/libs/*.jar
